development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: orenagi_devel
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: localhost
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: orenagi_test
  username: root
  password: password
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: admin
  password: BwGz55yBfQOb
  socket: /var/lib/mysql/mysql.sock
  host: rds-intern.cc7ypgxhy74c.ap-northeast-1.rds.amazonaws.com
  database: orenagi
